<a href="https://colab.research.google.com/github/WilliamAshbee/DataminingAssignments/blob/main/DM_explore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sklearn as sk
import pandas as pd
import numpy as np


In [2]:
#!wget http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/cleve.mod

In [3]:
#url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/cleve.mod'
#df1 = pd.read_csv(url,header=None,skiprows=(i for i in range(20)),delim_whitespace=True,error_bad_lines=False)



In [4]:
pain = {'angina': 1, 'asympt': 4,'notang':2,'abnang':3}
gender = {'male':1,'fem':0}
bsl20 = {'true':1,'fal':0}
restingecg = {'norm':0,'abn':1, 'hyp':2}
exindang = {'true':1,'fal':0}
slope = {'up':1, 'flat':2, 'down':3}
thal = {'norm':1, 'fix':2, 'rev':3}
state= {'buff':1,'sick':-1}
code = {'H':0,'S1':1,'S2':2,'S3':3,'S4':4}
eleventh = {'?':-10000}
twelth = {'?':-10000}
#df2 = df1.replace({1: gender,2:pain,5:bsl20,6:restingecg,8:exindang,10:slope,11:eleventh,12:{**thal, **twelth},13:state,14:code})


In [5]:
#https://stackoverflow.com/questions/17114904/python-pandas-replacing-strings-in-dataframe-with-numbers
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html

In [6]:
#df2.tail()

In [7]:

#df2n = df2.to_numpy().astype(float)

#df2n.shape


In [8]:
url2 = 'http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data'
df_clev = pd.read_csv(url2,header=None,error_bad_lines=False)

In [9]:
questionmark = {'?':'-10000'}

dfcn = df_clev
dfcn = dfcn.replace({11:questionmark,12:questionmark})
dfcn = dfcn.to_numpy().astype(float)

print(np.sum(dfcn=='?'))#,np.sum(df2n=='?'))

0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  import sys


In [10]:
import sklearn as sk
from sklearn.linear_model import LogisticRegression
import os
#change here
y = dfcn[:,13]

X = dfcn[:,:13]

LR = LogisticRegression(max_iter = 100000,random_state=0, solver='lbfgs', multi_class='auto').fit(X, y)
round(LR.score(X,y), 5)


0.62046

In [11]:
out = LR.predict(X)

In [12]:
from sklearn import svm
clf = svm.SVC(decision_function_shape='ovo')
print(clf.kernel)
clf = clf.fit(X, y)
out = clf.predict(X)
print(np.mean(out==y))

rbf
0.5412541254125413


In [13]:
C_2d_range = [1e-2, 1, 1e2]
gamma_2d_range = [1e-1, 1, 1e1]
classifiers = []
for C in C_2d_range:
    for gamma in gamma_2d_range:
        clf = svm.SVC(C=C, gamma=gamma,decision_function_shape='ovo')
        clf.fit(X, y)
        out = clf.predict(X)
        if np.mean(y==out) > .6:
          print(np.mean(y==out),C,gamma)
        classifiers.append((C, gamma, clf,np.mean(y==out)))

clf = svm.SVC(C=1, gamma=.1,decision_function_shape='ovo')
clf.fit(X, y)
clf.predict(X)

1.0 1 0.1
1.0 1 1
1.0 1 10.0
1.0 100.0 0.1
1.0 100.0 1
1.0 100.0 10.0


array([0., 2., 1., 0., 0., 0., 3., 0., 2., 1., 0., 0., 2., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 3., 4., 0., 0., 0., 0., 3., 0., 2., 1., 0.,
       0., 0., 3., 1., 3., 0., 4., 0., 0., 0., 1., 4., 0., 4., 0., 0., 0.,
       0., 2., 0., 1., 1., 1., 1., 0., 0., 2., 0., 1., 0., 2., 2., 1., 0.,
       2., 1., 0., 3., 1., 1., 1., 0., 1., 0., 0., 3., 0., 0., 0., 3., 0.,
       0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0.,
       0., 0., 3., 0., 2., 1., 2., 3., 1., 1., 0., 2., 2., 0., 0., 0., 3.,
       2., 3., 4., 0., 3., 1., 0., 3., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
       4., 3., 1., 0., 0., 1., 0., 1., 0., 1., 4., 0., 0., 0., 0., 0., 0.,
       4., 3., 1., 1., 1., 2., 0., 0., 4., 0., 0., 0., 0., 0., 0., 1., 0.,
       3., 0., 1., 0., 4., 1., 0., 1., 0., 0., 3., 2., 0., 0., 1., 0., 0.,
       2., 1., 2., 0., 3., 1., 2., 0., 3., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 3., 3., 3., 0., 1., 0., 4., 0., 3., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 3., 1., 0.

In [14]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=1, max_iter=30000,learning_rate_init = .00001).fit(X, y)
clf.predict(X)
clf.score(X, y)


0.594059405940594

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
#X, y = make_classification(n_samples=1000, n_features=4,
#...                            n_informative=2, n_redundant=0,
#...                            random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=7, random_state=0)
clf.fit(X, y)
print(clf.score(X,y))


0.9702970297029703


In [16]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X, y)
gnb_score = gnb.score(X,y)
print(gnb_score)

0.18151815181518152


In [17]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(X, y)
print(neigh.score(X,y))

0.6567656765676567


In [18]:
#https://medium.com/@rrfd/boosting-bagging-and-stacking-ensemble-methods-with-sklearn-and-mlens-a455c0c982de

In [19]:
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score

clf = KNeighborsClassifier()
clf.fit(X,y)
bagging_clf = BaggingClassifier(clf, max_samples=0.4, max_features=4, random_state=0)
bagging_scores = cross_val_score(bagging_clf, X, y, cv=10, n_jobs=-1)
print(bagging_scores)
knnscores = cross_val_score(clf, X, y, cv=10, n_jobs=-1)
print(knnscores)

[0.5483871  0.5483871  0.58064516 0.6        0.56666667 0.66666667
 0.56666667 0.53333333 0.53333333 0.53333333]
[0.5483871  0.48387097 0.51612903 0.56666667 0.53333333 0.4
 0.53333333 0.53333333 0.33333333 0.53333333]


In [20]:
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(base_estimator=None)
clf.fit(X,y)
clf.score(X,y)
cross_val_score(clf, X, y, cv=10, n_jobs=-1)

array([0.67741935, 0.58064516, 0.5483871 , 0.66666667, 0.53333333,
       0.46666667, 0.5       , 0.43333333, 0.46666667, 0.46666667])

In [21]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
grad_boost = GradientBoostingClassifier()
cross_val_score(grad_boost, X, y, cv=10, n_jobs=-1)

array([0.64516129, 0.51612903, 0.61290323, 0.56666667, 0.63333333,
       0.46666667, 0.46666667, 0.66666667, 0.53333333, 0.56666667])

In [22]:
#
from sklearn.ensemble import ExtraTreesClassifier, VotingClassifier
from sklearn.linear_model import RidgeClassifier
rf = RandomForestClassifier()
et = ExtraTreesClassifier()
knn = KNeighborsClassifier()
svc = svm.SVC()
rg = RidgeClassifier()

clf = [rf, et, knn, svc, rg]
eclf = VotingClassifier(estimators=[('Random Forests', rf), ('Extra Trees', et), ('KNeighbors', knn), ('SVC', svc), ('Ridge Classifier', rg)], voting='hard')
for clf, label in zip([rf, et, knn, svc, rg, eclf], ['Random Forest', 'Extra Trees', 'KNeighbors', 'SVC', 'Ridge Classifier', 'Ensemble']):
    scores = cross_val_score(clf, X, y, cv=10, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))


Accuracy: 0.58 (+/- 0.06) [Random Forest]
Accuracy: 0.58 (+/- 0.07) [Extra Trees]
Accuracy: 0.50 (+/- 0.07) [KNeighbors]
Accuracy: 0.54 (+/- 0.01) [SVC]
Accuracy: 0.56 (+/- 0.03) [Ridge Classifier]
Accuracy: 0.56 (+/- 0.04) [Ensemble]


In [23]:
from sklearn.metrics import f1_score
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
f1_score(y_true, y_pred, average=None)



array([0.8, 0. , 0. ])

In [24]:
from sklearn import metrics
scores = cross_val_score(
clf, X, y, cv=5, scoring='f1_macro')


In [25]:
scores

array([0.20348837, 0.25273002, 0.19058824, 0.22196078, 0.2549779 ])

In [26]:
#https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc_crossval.html

In [30]:
#note multiclass roc curve is a little poorly defined, so i went with
#solution from: https://medium.com/@plog397/auc-roc-curve-scoring-function-for-multi-class-classification-9822871a6659

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import plot_roc_curve
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.metrics import roc_auc_score


cv = StratifiedKFold(n_splits=10)
#y = np.expand_dims(y.squeeze(), axis=1)
y = y.squeeze()
#classifier = svm.SVC(kernel='linear',decision_function_shape='ovo', probability=True,
#                     random_state=0)
#classifier = KNeighborsClassifier(n_neighbors=k)

#classifier = RandomForestClassifier(max_depth=d,n_estimators = n_est random_state=0)

#classifier = LogisticRegression(max_iter = 10**(ite),random_state=0, solver='lbfgs', multi_class='auto')

# classifier = MLPClassifier(random_state=1, max_iter=10**(ite),learning_rate_init = 10**(lr)) 
#code from link above in note (medium)
def multiclass_roc_auc_score(y_test, y_pred, average="macro"):
  lb = preprocessing.LabelBinarizer()
  lb.fit(y_test)
  y_test = lb.transform(y_test)
  y_pred = lb.transform(y_pred)
  return roc_auc_score(y_test, y_pred, average=average)
for epoch in range(1):
  for smooth in range(-6,-12,-1):
    classifier = GaussianNB(var_smoothing = 10**(smooth))

    for i, (train, test) in enumerate(cv.split(X, y)):
      print('\n',i,smooth)
      classifier.fit(X[train], y[train])
      y_pred = classifier.predict(X[test])
      print("score",classifier.score(X[test],y[test]))
      print('auc score',multiclass_roc_auc_score(y[test],y_pred))
      print('f1 score', f1_score(y[test], y_pred, average='macro'))
    


 0 -6
score 0.06451612903225806
auc score 0.4638341543513958
f1 score 0.02857142857142857

 1 -6
score 0.0967741935483871
auc score 0.5003694581280789
f1 score 0.038709677419354833

 2 -6
score 0.0967741935483871
auc score 0.5
f1 score 0.03636363636363636

 3 -6
score 0.1
auc score 0.5007662835249042
f1 score 0.039999999999999994

 4 -6
score 0.1
auc score 0.5002554278416348
f1 score 0.0375

 5 -6
score 0.13333333333333333
auc score 0.5014376657824934
f1 score 0.05517241379310346

 6 -6
score 0.16666666666666666
auc score 0.5077802197802198
f1 score 0.11282051282051282

 7 -6
score 0.06666666666666667
auc score 0.43901098901098895
f1 score 0.034782608695652174

 8 -6
score 0.13333333333333333
auc score 0.5
f1 score 0.047058823529411764

 9 -6
score 0.1
auc score 0.4728355437665782
f1 score 0.04444444444444444

 0 -7
score 0.03225806451612903
auc score 0.4269343185550082
f1 score 0.021052631578947368

 1 -7
score 0.0967741935483871
auc score 0.49963546798029557
f1 score 0.0428571428571

In [28]:
print(X.shape)

(303, 13)
